CREATE DATABASE chat;

USE chat;

CREATE TABLE messages (
  id INTEGER(3) AUTO_INCREMENT,
  roomname VARCHAR(25),
  message VARCHAR(500),
  PRIMARY KEY (ID)
  
);

CREATE TABLE users (
  id INTEGER(3) AUTO_INCREMENT,
  username VARCHAR(25) NOT NULL,
  PRIMARY KEY (ID)
);
